### PR TITLE
Context-aware flag

### PR DESCRIPTION
**Pull request by ncounter**
## Changes

Issue https://github.com/kubewarden/policy-hub/issues/45

Below you can see the case `context-aware: true` with the `sync` icon as @flavio suggested it is the one that makes the most of the meaning of the flag. The `context-aware: false` case will not be visible instead.

`context-aware` ON:
context-aware-on

## Before merging this PR
@ereslibre : I'd need a change to let the frontend code be more clean and simple (it can still work anyway, but I'd prefer to keep it in a good shape if possible). Would it be a problem to rename the `context-aware` key in the JSON to `contextAware`? JS is not so happy with `-` (dashes) in key names when it translates it into an Object, better to use camelCase instead :expressionless:

### CODE REVIEW

**Comment by flavio** [comment]
I just realized the majority of the policies will NOT be context-aware, meaning the "not sync" icon will be everywhere on the page. Isn't this going to clutter everything?

Maybe we should show the "sync" icon only when a policy is context-aware. What do you think?

**Comment by ncounter** [comment]
> I just realized the majority of the policies will NOT be context-aware, meaning the "not sync" icon will be everywhere on the page. Isn't this going to clutter everything?
> 
> Maybe we should show the "sync" icon only when a policy is context-aware. What do you think?

I'd agree with that, yes, until the both of the following statement are still true:
- the most of the policies will be "NOT context-aware"
- the fact that a policy is "NOT context-aware" **is not so relevant** compared to the case when **it is** "context-aware".

I'll adapt the PR accordingly then, removing the case of "NOT context-aware". :+1:

**Comment by flavio** [comment]
> @ereslibre : I'd need a change to let the frontend code be more clean and simple (it can still work anyway, but I'd prefer to keep it in a good shape if possible). Would it be a problem to rename the context-aware key in the JSON to contextAware? JS is not so happy with - (dashes) in key names when it translates it into an Object, better to use camelCase instead expressionless

I think we can make this change

**Comment by ereslibre** [comment]
Yes, we can rename it to `contextAware`.

**Comment by ereslibre** [comment]
@ncounter @flavio: all policies are updated now :tada:

**Pull request merged**
