### PR TITLE
Add banner for Artifact Hub migration

### LINKED ISSUE #191: Update policy hub landing page
We want to make our users aware that all the Kubewarden polices are now published on Artifact Hub.

We envisioned two possible ways to achieve that, it all depends on how complex it is to implement them.

# Banner (preferred solution)

Display a banner at the top of the page. The banner will state that all our policies are now on Artifact Hub. It will also have two links inside of it:
  * Link to the Artifact Hub page that shows all the Kubewarden policies. (For example, this is the [staging URL](https://staging.artifacthub.io/packages/search?kind=13&sort=relevance&page=1))
  * Link to the blog post where we announce this news

# Replace old landing page

Just show a static html page when visiting `hub.kubewarden.io`. The page will show the same information written above

### PR DESCRIPTION
**Pull request by jordojordo**
## Description

Fix #191 

## Test

To test this pull request, you can run the following commands:
```shell
cd web
yarn install
yarn start
```

## Additional Information
I decided to go with the banner approach as to not take away from the work that @ncounter has contributed. 

The two urls for Artifact Hub and the blog post will need to be updated once both are in place.

### Tradeoff
As for the placement of the banner this is up to preference and can easily be set to where we decide. Also the wording could be different (I'm definitely not a writer!).

banner

### CODE REVIEW

**Review by viccuad — APPROVED** [review]
LGTM! Thanks! Allow me to make the PR a draft one for now just in case.

**Review by jvanz — APPROVED** [review]

**Review by flavio — APPROVED** [review]
I :heart: it! Thanks!

**Comment by jvanz** [comment]
As we have all the policies in Artifacthub, I'm marking this PR as ready for review. I think we can merge it right away.

**Comment by jvanz** [comment]
> As we have all the policies in Artifacthub, I'm marking this PR as ready for review. I think we can merge it right away.

@flavio remembered that we need to add the link to the blog post to be released yet. Thus, we need to wait a little bit more.

**Comment by flavio** [comment]
I've updated the links!

**Pull request merged**
